export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const CHANGE_PAYMENT_METHOD = 'CHANGE_PAYMENT_METHOD';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_DETAILS_ORDER = 'CHANGE_DETAILS_ORDER';
export const ERROR_CHANGE_DETAILS_ORDER = "ERROR_CHANGE_DETAILS_ORDER";
export const SERVER_ANSWER = "SERVER_ANSWER";
export const SERVER_ANSWER_CLEAN = "SERVER_ANSWER_CLEAN";
