import React, { Component } from 'react'
import { Table, Tag, Divider } from 'antd'
import uuidv4 from 'uuid/v4'

class TableReportes extends Component {
  render() {
    const { columns, data } = this.props
    return (
      <Table
        pagination={{
          total: data.length,
          defaultCurrent: 1,
          showSizeChanger: true,
          showTotal: (total, range) => `${range[0]}-${range[1]} de ${total} elementos`,
          pageSizeOptions: ['10', '20', '30', '40'],
        }}
        columns={columns}
        dataSource={data}
        bordered
      />
    )
  }
}

TableReportes.defaultProps = {
  data: [
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta de transacciones',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
    {
      key: uuidv4(),
      report: 'Consulta',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer', 'loser'],
    },
    {
      key: uuidv4(),
      report: 'Ventas codigo de terminal',
      periodo: '12-09-2020',
      solicited: 'Leonardo',
      downloaded_date: 'ASD 12-09-2020',
      status: ['nice', 'developer'],
    },
  ],
  columns: [
    {
      title: 'Reporte',
      dataIndex: 'report',
      key: 'report',
      render: text => <a>{text}</a>,
      sorter: (a, b) => a.report - b.report,
      sortDirections: ['descend', 'ascend'],
    },
    {
      title: 'Periodo',
      dataIndex: 'periodo',
      key: 'periodo',
      sorter: (a, b) => a.periodo - b.periodo,
      sortDirections: ['descend', 'ascend'],
    },
    {
      title: 'Solicitado por',
      dataIndex: 'solicited',
      key: 'solicited',
      sorter: (a, b) => a.solicited - b.solicited,
      sortDirections: ['descend', 'ascend'],
    },
    {
      title: 'Ultima descarga',
      dataIndex: 'downloaded_date',
      key: 'downloaded_date',
      sorter: (a, b) => a.downloaded_date - b.downloaded_date,
      sortDirections: ['descend', 'ascend'],
    },
    {
      title: 'Estado',
      key: 'status',
      dataIndex: 'status',
      render: tags => (
        <span>
          {tags.map(tag => {
            let color = tag.length > 5 ? 'geekblue' : 'green'
            if (tag === 'loser') {
              color = 'volcano'
            }
            return (
              <Tag color={color} key={tag}>
                {tag.toUpperCase()}
              </Tag>
            )
          })}
        </span>
      ),
    },
    {
      title: 'Action',
      key: 'action',
      render: (text, record) => (
        <span>
          <a>Descargar {record.name}</a>
          <Divider type="vertical" />
          <a>Actualizar</a>
        </span>
      ),
    },
  ],
}

export default TableReportes
